# Generated by Django 5.2.4 on 2025-08-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='french_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
