# Generated by Django 5.2.4 on 2025-08-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_french_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='french_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
