# Generated by Django 5.2.4 on 2025-08-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animal_french_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='french_name',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='scientific_name',
        ),
        migrations.AddField(
            model_name='animal',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
