# Generated by Django 5.2.4 on 2025-08-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_remove_animal_french_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='french_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
