# Generated by Django 5.2.4 on 2025-08-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_remove_animal_french_name_animal_scientific_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='wikidata_id',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='wikipedia_title',
        ),
        migrations.AddField(
            model_name='animal',
            name='french_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
