# Generated by Django 5.2.4 on 2025-08-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_remove_animal_scientific_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='french_name',
        ),
        migrations.AddField(
            model_name='animal',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='wikidata_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='wikipedia_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='animal',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
