# Generated by Django 5.2.4 on 2025-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_remove_animal_french_name_animal_scientific_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='french_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
