# Generated by Django 5.2.4 on 2025-08-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
